[project]

name = "emailer"
version = "0.1.0"
description = "Send Email to Students"
authors = [
    {name = "Simson Garfinkel", email = "simsong@acm.org"}
]
readme = "README.md"
requires-python = "^3.13"
dependencies = [
    "msal (>=1.34.0,<2.0.0)",
    "keyring (>=25.7.0,<26.0.0)"
]
[tool.poetry]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
